# For full config options, check the docs:
#    docs.serverless.com
service: rating-service

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, file(serverless.env.yml):stage}
  region: ${opt:region, file(serverless.env.yml):region}
  profile: ${opt:profile, file(serverless.env.yml):profile}
  project: rating-service
  memorySize: 256 # MB
  timeout: 10 # Seconds
  cfLogs: true,
  environment:
    SERVERLESS_PROJECT: ${self:provider.project}
    SERVERLESS_REGION: ${self:provider.region}
    SERVERLESS_STAGE: ${self:provider.stage}
    RATING_TABLE: ${self:service}-${self:provider.stage}-rating
    RATING_TABLE_INDEX_CONTENT_ID: content_id_index
  iamRoleStatements: ${file(./serverless.iam.yml):iamRoleStatements}

package:
  exclude:
    - node_modules/**
    - test/**

resources: ${file(./serverless.resources.yml)}

functions: ${file(./serverless.functions.js)}
  
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    port: 4000

plugins:
  - serverless-offline
  - serverless-webpack
